rails decidim:delete_data_portability_files
rails decidim:metrics:all
rails decidim:open_data:export
rails decidim_meetings:clean_registration_forms
rails decidim_initiatives:check_published
rails decidim_initiatives:check_validating
rails decidim_initiatives:notify_progress
